server:
  port: 8050
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: characterRoute
          uri: lb://character-service
          predicates:
            - Path=/characters/**
        - id: movieCharacterRoute
          uri: lb://movie-character-service
          predicates:
            - Path=/series/**
        - id: movieCharacterRoute
          uri: lb://movie-character-service
          predicates:
            - Path=/movies-characters/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
